### PR TITLE
Feature/jwt

### PR DESCRIPTION
**Pull request by hakobyansen**

### CODE REVIEW

**Comment by hakobyansen** [comment]
@raphbibus  please explain the purpose of "clients" table. We have User model and Client model, but we don't have "users" table in the database.

Depending on the purpose of "clients" table we may need to add "password" column and make the Client model to be Authenticatable, or create a new "users" table and implement user<->client relation.

I need clarifications about users/clients schema and if we need both tables - the relation between them.

**Comment by ralphcibis-thomann** [comment]
the User model is still the out-of-the-box model from Lumen. I think the easier way to go would be to make Client authenticatable and drop the User model.

**Comment by hakobyansen** [comment]
@raphbibus you can probably review this PR.

**Comment by ralphcibis-thomann** [comment]
Thanks @c0d3b0t for implementing it so quickly! I will merge the PR this week. 

I just have to move the dev environment for the app to another branch first that the currently used API won't break.

**Review by ralphcibis-thomann — APPROVED** [review]

**Comment by ralphcibis-thomann** [comment]
Awesome PR! Thank you so much for your help here! I have a call with the hackathon team on Sunday. Hopefully, they want to develop more on the app side and implement the JWT auth there.

**Pull request merged**
